---
- name: after_rhel7_os_install
  hosts: all
  tasks:
   - name: install_ntp
     yum: name=ntp state=latest

   - name: install_wget
     yum: name=ntpdate state=latest

   - name: ntp_server_config
     lineinfile: dest=/etc/ntp.conf line="server 172.27.0.200" state=present backup=yes

   - name: ntp_server_config_2
     lineinfile: dest=/etc/ntp.conf line="server 172.27.0.201" state=present backup=yes
