---
- name: after_rhel7_os_install
  hosts: all
  vars:
   proxy_env:
    http_proxy: http://172.27.0.205:3128

  tasks:
   - name: system_wide_proxy_http
     lineinfile: dest=/etc/profile.d/proxy.sh line="export http_proxy=http://172.27.0.205:3128" state=absent backup=yes create=yes

   - name: system_wide_proxy_ftp
     lineinfile: dest=/etc/profile.d/proxy.sh line="export ftp_proxy=http://172.27.0.205:3128" state=absent backup=yes
